#!/usr/bin/env node
/**
 * generate-summary.js
 * Auto-generates human-readable SUMMARY.md from STATUS.json and TASKS.json
 * 
 * Usage: node scripts/generate-summary.js
 */

const fs = require('fs');
const path = require('path');

// Load JSON files
function loadJSON(filename) {
  try {
    const filePath = path.join(process.cwd(), '.ai', filename);
    const content = fs.readFileSync(filePath, 'utf-8');
    return JSON.parse(content);
  } catch (error) {
    console.error(`❌ Error loading ${filename}: ${error.message}`);
    process.exit(1);
  }
}

// Format date
function formatDate(dateString) {
  if (!dateString) return 'N/A';
  const date = new Date(dateString);
  return date.toLocaleString('id-ID', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
}

// Generate status emoji
function getStatusEmoji(status) {
  const emojis = {
    'healthy': '🟢',
    'at_risk': '🟡',
    'critical': '🔴',
    'unknown': '⚪'
  };
  return emojis[status] || '⚪';
}

// Generate summary content
function generateSummary() {
  console.log('📝 Generating SUMMARY.md...');

  const status = loadJSON('STATUS.json');
  const tasks = loadJSON('TASKS.json');
  const changelog = fs.readFileSync(path.join(process.cwd(), '.ai', 'CHANGELOG.md'), 'utf-8');

  // Calculate metrics
  const totalTasks = tasks.tasks.length;
  const completedTasks = tasks.tasks.filter(t => t.status === 'completed').length;
  const inProgressTasks = tasks.tasks.filter(t => t.status === 'in_progress').length;
  const blockedTasks = status.critical_blockers ? status.critical_blockers.filter(b => b.status === 'open').length : 0;

  // Get recent completed tasks
  const recentCompleted = status.recently_completed || [];

  // Build markdown content
  let md = `# 📊 KALKULATOR WARIS ISLAM - PROJECT SUMMARY\n\n`;
  md += `**Generated:** ${formatDate(new Date().toISOString())}\n`;
  md += `**Generated by:** Auto-Summary Script\n`;
  md += `**Project Status:** 🔄 IN PROGRESS - ${status.current_phase.name}\n\n`;
  md += `---\n\n`;

  // Quick Overview
  md += `## 🎯 Quick Overview\n\n`;
  md += `| Metric | Value | Status |\n`;
  md += `|--------|-------|--------|\n`;
  md += `| **Overall Progress** | ${status.current_phase.progress}% | ${getStatusEmoji(status.current_phase.progress >= 50 ? 'healthy' : 'at_risk')} |\n`;
  md += `| **Current Phase** | ${status.current_phase.name} | ${status.current_phase.progress}% Complete |\n`;
  md += `| **Files Complete** | ${status.files_status.completed} / ${status.files_status.total} | ${Math.round(status.files_status.completed / status.files_status.total * 100)}% |\n`;
  md += `| **Critical Blockers** | ${blockedTasks} | ${blockedTasks > 0 ? '🔴 URGENT' : '✅ None'} |\n`;
  md += `| **Last Update** | ${formatDate(status.last_update)} | - |\n\n`;
  md += `---\n\n`;

  // What's Done Today
  md += `## ✅ What's Done Recently\n\n`;
  if (recentCompleted.length === 0) {
    md += `*No tasks completed in recent session*\n\n`;
  } else {
    md += `### Recently Completed (${recentCompleted.length} tasks)\n\n`;
    recentCompleted.slice(0, 5).forEach(item => {
      md += `- ✅ **${item.task}**\n`;
      md += `  - Completed: ${formatDate(item.completed_at)}\n`;
      md += `  - By: ${item.completed_by}\n`;
      if (item.files_affected) {
        md += `  - Files: ${item.files_affected.join(', ')}\n`;
      }
      md += `\n`;
    });
  }

  // What's In Progress
  md += `## 🔄 What's In Progress\n\n`;
  const inProgress = tasks.tasks.filter(t => t.status === 'in_progress');
  if (inProgress.length === 0) {
    md += `*No tasks currently in progress*\n\n`;
  } else {
    inProgress.forEach(task => {
      md += `- 🔄 **${task.id}:** ${task.title}\n`;
      md += `  - Priority: ${task.priority}\n`;
      md += `  - Started: ${formatDate(task.started_at)}\n`;
      md += `  - Assigned to: ${task.assigned_to || 'Unassigned'}\n\n`;
    });
  }

  // Critical Blockers
  md += `## 🚧 Critical Blockers\n\n`;
  if (blockedTasks === 0) {
    md += `✅ **No critical blockers!** Project is clear to proceed.\n\n`;
  } else {
    status.critical_blockers.forEach((blocker, idx) => {
      if (blocker.status === 'open') {
        md += `### ${getStatusEmoji('critical')} Blocker #${idx + 1}: ${blocker.issue}\n\n`;
        md += `- **Priority:** ${blocker.priority} - CRITICAL\n`;
        md += `- **Impact:** ${blocker.impact}\n`;
        md += `- **Action Required:** ${blocker.issue}\n\n`;
      }
    });
  }

  // Next Priorities
  md += `## 🎯 Next Priorities\n\n`;
  if (status.next_priorities && status.next_priorities.length > 0) {
    md += `### Must Do Next\n\n`;
    status.next_priorities.forEach((priority, idx) => {
      md += `${idx + 1}. ${priority}\n`;
    });
    md += `\n`;
  }

  // Progress Breakdown
  md += `## 📈 Progress Breakdown\n\n`;
  md += `### Files by Status\n\n`;
  md += `| Status | Count | Percentage |\n`;
  md += `|--------|-------|------------|\n`;
  md += `| ✅ Completed | ${status.files_status.completed} | ${Math.round(status.files_status.completed / status.files_status.total * 100)}% |\n`;
  md += `| 🔄 In Progress | ${status.files_status.in_progress} | ${Math.round(status.files_status.in_progress / status.files_status.total * 100)}% |\n`;
  md += `| ⏸️ Not Started | ${status.files_status.not_started} | ${Math.round(status.files_status.not_started / status.files_status.total * 100)}% |\n`;
  md += `| **Total** | **${status.files_status.total}** | **100%** |\n\n`;

  // Tasks Breakdown
  md += `### Tasks by Priority\n\n`;
  const p0Tasks = tasks.tasks.filter(t => t.priority === 'P0');
  const p1Tasks = tasks.tasks.filter(t => t.priority === 'P1');
  const p2Tasks = tasks.tasks.filter(t => t.priority === 'P2');

  md += `- 🔴 **P0 (Critical):** ${p0Tasks.filter(t => t.status === 'completed').length}/${p0Tasks.length} completed\n`;
  md += `- 🟠 **P1 (High):** ${p1Tasks.filter(t => t.status === 'completed').length}/${p1Tasks.length} completed\n`;
  md += `- 🟡 **P2 (Medium):** ${p2Tasks.filter(t => t.status === 'completed').length}/${p2Tasks.length} completed\n\n`;

  // Recommendations
  md += `## 💡 Recommendations\n\n`;
  if (blockedTasks > 0) {
    md += `🔴 **Urgent:** Resolve ${blockedTasks} critical blocker(s) before proceeding\n\n`;
  }
  if (status.files_status.completed / status.files_status.total < 0.25) {
    md += `⚠️ **Focus:** Less than 25% complete - focus on P0 tasks only\n\n`;
  }

  // Footer
  md += `---\n\n`;
  md += `**Last Updated:** ${formatDate(new Date().toISOString())}\n`;
  md += `**Next Update:** After next AI session completes a task\n`;
  md += `**Auto-generated by:** AI Briefing System v1.0\n`;

  return md;
}

// Main execution
try {
  const summaryContent = generateSummary();
  const outputPath = path.join(process.cwd(), '.ai', 'SUMMARY.md');

  fs.writeFileSync(outputPath, summaryContent, 'utf-8');

  console.log('✅ SUMMARY.md generated successfully!');
  console.log(`📁 Location: ${outputPath}`);
  console.log('\n📊 Summary Stats:');

  const status = loadJSON('STATUS.json');
  console.log(`   - Overall Progress: ${status.current_phase.progress}%`);
  console.log(`   - Files Complete: ${status.files_status.completed}/${status.files_status.total}`);
  console.log(`   - Critical Blockers: ${status.critical_blockers ? status.critical_blockers.filter(b => b.status === 'open').length : 0}`);

} catch (error) {
  console.error(`❌ Error generating summary: ${error.message}`);
  process.exit(1);
}
